// Full WMI database merged from:
// 1. WALL-E/vin-decoder (github) — 436 entries from Wikibooks
// 2. Custom CIS/CN truck entries not in public databases
// Key: WMI (3 chars), Value: manufacturer name

export const WMI_DATABASE: Record<string, string> = {
  // Africa
  "AAV": "Volkswagen South Africa",
  "AC5": "Hyundai South Africa",
  "ADD": "Hyundai South Africa",
  "AFA": "Ford South Africa",
  "AHT": "Toyota South Africa",

  // Japan
  "JA3": "Mitsubishi",
  "JA4": "Mitsubishi",
  "JA": "Isuzu",
  "JD": "Daihatsu",
  "JF": "Fuji Heavy Industries (Subaru)",
  "JH": "Honda",
  "JK": "Kawasaki",
  "JL5": "Mitsubishi Fuso",
  "JMB": "Mitsubishi Motors",
  "JMY": "Mitsubishi Motors",
  "JMZ": "Mazda",
  "JN": "Nissan",
  "JS": "Suzuki",
  "JT": "Toyota",
  "JY": "Yamaha",
  "JHM": "Honda",
  "JNK": "Infiniti",
  "JN1": "Nissan",
  "JN6": "Nissan (light commercial)",
  "JN8": "Nissan",
  "JHL": "Honda",
  "JF1": "Subaru",
  "JF2": "Subaru",
  "JS1": "Suzuki",
  "JS2": "Suzuki",
  "JS3": "Suzuki",
  "JT2": "Toyota",
  "JT3": "Toyota",
  "JT4": "Toyota (light trucks)",
  "JT6": "Lexus",
  "JT7": "Toyota",
  "JT8": "Lexus",

  // Korea
  "KL": "Daewoo / GM Korea",
  "KM": "Hyundai",
  "KMY": "Daelim",
  "KM1": "Hyosung",
  "KN": "Kia",
  "KNM": "Renault Samsung",
  "KPA": "SsangYong",
  "KPT": "SsangYong",
  "KMH": "Hyundai",
  "KMJ": "Hyundai",
  "KMU": "Hyundai (buses/trucks)",
  "KNA": "Kia",
  "KNB": "Kia",
  "KND": "Kia",

  // China
  "LAN": "Changzhou Yamasaki",
  "LBB": "Geely",
  "LBE": "Beijing Benz",
  "LBP": "Geely",
  "LBV": "HOWO / Sinotruk",
  "LCE": "Changan",
  "LDC": "Dongfeng",
  "LDN": "Dongfeng (Nissan)",
  "LDY": "Dongfeng",
  "LE4": "Shacman (Shaanxi Automobile)",
  "LEA": "Guangzhou Honda",
  "LET": "Jiangling-Isuzu",
  "LFB": "FAW",
  "LFG": "Taizhou Chuanl",
  "LFP": "FAW",
  "LFT": "FAW",
  "LFV": "FAW-Volkswagen",
  "LFW": "FAW JieFang",
  "LF2": "Foton",
  "LGC": "Jincheng",
  "LGX": "GAC (Guangzhou Automobile)",
  "LH1": "FAW-Haima",
  "LHG": "Guangzhou Honda",
  "LJ1": "Beijing Jeep",
  "LJD": "Jiangling (JMC)",
  "LKL": "Suzhou King Long (buses)",
  "LL6": "Hunan Changfeng",
  "LLN": "Qoros",
  "LMG": "Suzuki (China)",
  "LMV": "Zhonghua",
  "LPC": "Shanghai GM (Buick)",
  "LSG": "Shanghai GM",
  "LSJ": "MG / SAIC",
  "LSV": "Shanghai-Volkswagen",
  "LTN": "Anhui Ankai (buses)",
  "LUZ": "Chery",
  "LVH": "Volvo China",
  "LVS": "Ford China",
  "LVV": "Volvo Trucks China",
  "LWV": "Volkswagen Changchun",
  "LXG": "Shacman",
  "LXV": "Ssangyong (China)",
  "LYV": "Volvo China",
  "LZA": "Kia (China)",
  "LZE": "Isuzu Guangzhou",
  "LZM": "MAN China",
  "LZZ": "HOWO / Sinotruk",
  "LB1": "FAW-Toyota",
  "LB2": "Changan Ford",
  "LC2": "Changan",
  "LC6": "Changan",
  "LD6": "Dongfeng",
  "LE2": "BYD",
  "LE3": "Dongfeng (Peugeot)",
  "LF3": "BYD",
  "LF4": "BYD",
  "LH4": "FAW-Haima",
  "LL3": "Lifan",
  "LL5": "Brilliance (Zhonghua)",
  "LMF": "Nanjing MF",
  "LP1": "BYD",
  "LP9": "Geely",
  "LRB": "Geely (Lynk & Co)",
  "LSC": "SAIC",
  "LV8": "GAC",
  "LW6": "Liuzhou Wuling",
  "LWL": "Chery",
  "LX3": "Geely",
  "LYB": "BAIC (Beijing Automotive)",
  "LYK": "Yutong (buses)",
  "LYM": "Yutong (buses)",
  "L5N": "Changan",
  "L56": "Zhejiang Yongkang",
  "L6T": "Chery",
  "L8X": "Chery",

  // India
  "MAT": "Tata Motors",
  "MA1": "Mahindra",
  "MA3": "Maruti Suzuki",
  "MA6": "Mahindra",
  "MB1": "Ashok Leyland",
  "MBR": "Mercedes-Benz India",
  "MC2": "Volvo Eicher",
  "MDH": "Hero Honda",
  "MEE": "Renault India",
  "MEC": "Mercedes-Benz India",
  "MHF": "Toyota Kirloskar",
  "MNT": "Nissan India",
  "MP1": "Isuzu Thailand",
  "MPA": "Isuzu Thailand",
  "MPB": "Mitsubishi Thailand",
  "MR0": "Mitsubishi Thailand",
  "MRH": "Honda Thailand",
  "MS0": "Suzuki Thailand",
  "MS3": "Isuzu Thailand",
  "MS6": "Mazda Thailand",
  "MM8": "Mazda Thailand",
  "M70": "Mitsubishi India",

  // Europe — Germany
  "NLE": "Mercedes-Benz Türk Truck",
  "NMT": "Toyota Turkey",
  "NM0": "Ford Turkey",
  "NM4": "Hyundai Assan Turkey",
  "SAJ": "Jaguar",
  "SAL": "Land Rover",
  "SB1": "Toyota UK",
  "SCB": "Bentley",
  "SCC": "Lotus",
  "SFD": "Alexander Dennis (buses)",
  "SHH": "Honda UK",
  "SJN": "Nissan UK",
  "SKF": "Vauxhall",
  "SLA": "Land Rover",
  "SMT": "Triumph (motorcycles)",
  "SNN": "LTI (London Taxi)",
  "SUF": "Rolls-Royce",
  "TCC": "Bentley",
  "TMA": "Hyundai Czech",
  "TMB": "Škoda",
  "TMP": "Škoda Octavia",
  "TMT": "Škoda Fabia",
  "TMK": "Škoda",
  "TRU": "Audi Hungary",
  "TSM": "Suzuki Hungary",
  "TW1": "Toyota Czech",
  "UU1": "Renault Dacia Romania",
  "UU6": "Daewoo Romania",
  "UU3": "Ford Romania",
  "VAN": "MAN Austria",
  "VF1": "Renault",
  "VF2": "Renault",
  "VF3": "Peugeot",
  "VF4": "Talbot / Matra",
  "VF6": "Renault Trucks",
  "VF7": "Citroën",
  "VF8": "Citroën",
  "VF9": "Bugatti",
  "VLU": "Scania France",
  "VNA": "Renault Trucks",
  "VNE": "Renault Trucks",
  "VNJ": "Renault Trucks",
  "VNK": "Renault Trucks",
  "VNV": "Renault-Nissan",
  "VSA": "Mercedes-Benz Spain",
  "VSE": "SEAT",
  "VSK": "Nissan Spain",
  "VSS": "SEAT",
  "VX1": "Citroën Spain",
  "WBA": "BMW",
  "WBS": "BMW M",
  "WBX": "BMW X",
  "WDB": "Mercedes-Benz",
  "WDC": "Mercedes-Benz (SUV)",
  "WDD": "Mercedes-Benz",
  "WDF": "Mercedes-Benz (Vans/Trucks)",
  "WDX": "Chrysler (Germany)",
  "WEB": "Mercedes-Benz (Buses)",
  "WF0": "Ford Germany",
  "WJM": "Iveco Magirus",
  "WKK": "Kawasaki Germany",
  "WMA": "MAN",
  "WMK": "MAN",
  "WM1": "MAN",
  "WMW": "MINI",
  "WMX": "Mercedes-AMG",
  "WP0": "Porsche",
  "WP1": "Porsche (Cayenne)",
  "WUA": "Audi quattro GmbH",
  "WV1": "Volkswagen Commercial",
  "WV2": "Volkswagen Bus",
  "WV3": "Volkswagen Trucks",
  "WVG": "Volkswagen (Touareg)",
  "WVW": "Volkswagen",
  "W0L": "Opel / Vauxhall",
  "XL9": "DAF",
  "XLA": "DAF",
  "XLB": "Volvo (NedCar)",
  "XLE": "Scania Netherlands",
  "XLR": "DAF Trucks",
  "XMC": "Mitsubishi Netherlands",
  "YCM": "Mazda Belgium",
  "YK1": "Saab",
  "YS2": "Scania",
  "YS3": "Saab / Scania",
  "YS4": "Scania (Buses)",
  "YSB": "Scania",
  "YTN": "Saab",
  "YV1": "Volvo Cars",
  "YV2": "Volvo Trucks",
  "YV3": "Volvo Buses",
  "YV4": "Volvo",
  "ZAM": "Maserati",
  "ZAP": "Alfa Romeo",
  "ZAR": "Alfa Romeo",
  "ZCF": "Iveco",
  "ZCG": "Iveco",
  "ZDM": "Ducati",
  "ZFA": "Fiat",
  "ZFF": "Ferrari",
  "ZHW": "Lamborghini",
  "ZJN": "Jeep Italy",
  "ZLA": "Lancia",

  // Czech / Slovakia
  "TJ3": "Zetor (tractors)",
  "TAA": "Tatra",
  "TAB": "Tatra",

  // Russia / CIS
  "X4W": "КАМАЗ",
  "XTC": "КАМАЗ",
  "XTT": "КАМАЗ",
  "X89": "КАМАЗ",
  "XWB": "КамАЗ",
  "Y3M": "МАЗ",
  "XUM": "МАЗ",
  "Y6D": "МАЗ",
  "XUF": "МАЗ",
  "X96": "ГАЗ",
  "XUU": "ГАЗ",
  "X4X": "ГАЗ",
  "XTH": "ЗИЛ",
  "XVN": "УРАЛ",
  "X7R": "УРАЛ",
  "XCE": "КрАЗ (Украина)",
  "Y7A": "Богдан (Украина)",
  "X7L": "Renault AvtoFramos Russia",
  "XW8": "Volkswagen Russia",
  "XWE": "Ford Sollers Russia",
  "X3W": "Toyota Russia",
  "XA3": "BMW Russia",
  "XAM": "Mercedes-Benz Russia",

  // USA
  "1C3": "Chrysler",
  "1C4": "Jeep",
  "1C6": "RAM",
  "1FA": "Ford",
  "1FB": "Ford (buses)",
  "1FC": "Ford (trucks)",
  "1FD": "Ford (heavy)",
  "1FM": "Ford",
  "1FT": "Ford Truck",
  "1FU": "Freightliner",
  "1FV": "Freightliner",
  "1G1": "Chevrolet",
  "1G6": "Cadillac",
  "1GC": "Chevrolet (trucks)",
  "1GD": "GMC",
  "1GK": "GMC",
  "1GT": "GMC",
  "1GY": "Cadillac",
  "1HG": "Honda USA",
  "1J4": "Jeep",
  "1M1": "Mack Truck",
  "1M2": "Mack Truck",
  "1M3": "Mack Truck",
  "1M4": "Mack Truck",
  "1N4": "Nissan USA",
  "1N6": "Nissan Truck USA",
  "1NX": "Pontiac (Toyota NUMMI)",
  "1VW": "Volkswagen USA",
  "1XK": "Kenworth",
  "1XP": "Peterbilt",
  "1YJ": "Tesla",
  "2FM": "Ford Canada",
  "2FU": "Freightliner Canada",
  "2FV": "Freightliner Canada",
  "2G1": "Chevrolet Canada",
  "2G2": "Pontiac Canada",
  "2HG": "Honda Canada",
  "2HH": "Acura Canada",
  "2HK": "Honda SUV Canada",
  "2HM": "Hyundai Canada",
  "2T1": "Toyota Canada",
  "2T2": "Lexus Canada",
  "2WK": "Western Star",
  "2WL": "Western Star",
  "2WM": "Western Star",
  "3C4": "Chrysler Mexico",
  "3D7": "Dodge RAM Mexico",
  "3FA": "Ford Mexico",
  "3FE": "Ford Explorer Mexico",
  "3G1": "Chevrolet Mexico",
  "3HG": "Honda Mexico",
  "3N1": "Nissan Mexico",
  "3VW": "Volkswagen Mexico",
  "4JG": "Mercedes-Benz USA",
  "4T1": "Toyota USA",
  "4T3": "Toyota USA",
  "4US": "BMW USA",
  "4V1": "Volvo USA",
  "4V2": "Volvo USA",
  "4V3": "Volvo USA",
  "4V4": "Volvo USA",
  "4V5": "Volvo USA",
  "4V6": "Volvo USA",
  "4VL": "Volvo USA",
  "4VM": "Volvo USA",
  "4VZ": "Volvo USA",
  "5FN": "Honda USA",
  "5FR": "Acura USA",
  "5J6": "Honda USA",
  "5N1": "Nissan USA",
  "5NP": "Hyundai USA",
  "5TD": "Toyota USA",
  "5XY": "Kia USA",
  "5YJ": "Tesla",
  "6AB": "MAN Australia",
  "6F4": "Kenworth Australia",
  "6F5": "Kenworth Australia",
  "6FP": "Ford Australia",
  "6G1": "Holden",
  "6MM": "Mitsubishi Australia",
  "6T1": "Toyota Australia",
  "7FR": "Honda New Zealand",

  // South America
  "9BD": "Fiat Brazil",
  "9BM": "Mercedes-Benz Brazil",
  "9BS": "Scania Brazil",
  "9BW": "Volkswagen Brazil",
  "9FB": "Ford Brazil",
  "936": "Toyota Brazil",
  "93H": "Honda Brazil",
  "93Y": "Toyota Brazil",
  "8AG": "Chevrolet Argentina",
  "8AF": "Ford Argentina",
}

// Lookup by WMI (3-char exact, then 2-char prefix)
export function lookupWMI(wmi3: string): string | null {
  const key3 = wmi3.toUpperCase()
  if (WMI_DATABASE[key3]) return WMI_DATABASE[key3]
  // Try 2-char prefix (some entries use 2-char WMI)
  const key2 = key3.slice(0, 2)
  if (WMI_DATABASE[key2]) return WMI_DATABASE[key2]
  return null
}
